apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
  namespace: custom-metrics
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: custom-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: custom-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: custom-metrics
  labels:
    app: prometheus
    prometheus: custom-metrics
spec:
  baseImage: prom/prometheus
  version: v2.2.1
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      service-monitor: prometheus
  resources:
    requests:
      memory: 300Mi
  retention: 7d
  scrapeInterval: 30s
  evaluationInterval: 30s
  storage:
    class: ""
    selector: {}
    resources: {}
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: custom-metrics
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30999
    port: 9090
    targetPort: web
  selector:
    app: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor
  namespace: custom-metrics
  labels:
    service-monitor: prometheus
spec:
  selector:
    matchLabels:
      custom-metrics: prometheus
  namespaceSelector:
    any: true
  endpoints:
  - port: http
  - port: https
  - port: grpc
