apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  selector:
    app: helloworld
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: custom-metrics
  labels:
    custom-metrics: prometheus
spec:
  selector:
    app: helloworld
  ports:
  - protocol: TCP
    port: 9113
    targetPort: 9113
    name: http
